version: '2.2'

services:
  doclever:
    container_name: doclever
    image: taomaree/doclever
    ports:
    - 10000:10000
    environment:
    - DB_HOST=mongodb://mongo:27017/DOClever
    - PORT=10000
    - DB_FILE=/data/file
    - DB_IMG=/data/img
    - DB_TEMP=/data/temp
    links:
    - mongo:mongo
    command: ["bash", "-c", "node DOClever-$${VER}/Server/bin/www --db $${DB_HOST} --file $${DB_FILE} --img $${DB_IMG} --temp $${DB_TEMP} --port $${PORT}"]
    volumes:
    - /srv/doclever/data:/data
    
  mongo:
    image: mongo:4.0
    restart: unless-stopped
    container_name: "doclever-mongo"
    command: mongod --smallfiles --oplogSize 128 --replSet rep --storageEngine=wiredTiger
    volumes:
    - /srv/doclever/db:/data/db

  mongo-init-replica:
    image: mongo:4.0
    container_name: "doclever-mongo-init"
    command: ["bash", "-c", 'sleep 10 && mongo mongo/DOClever --eval "rs.initiate({ _id: ''rep'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"']
    depends_on:
      - mongo
